# ---------------------------------------------------------------
# $Id: Makefile 1796 2013-02-24 18:42:43Z viari $
# ---------------------------------------------------------------
# @file: Makefile
# @desc: makefile for LX library
#
# @history:
# @+	    <Gloup> : Mar 92 : first draft
# @+	    <Gloup> : Jul 93 : revised version
# @+	    <Gloup> : Feb 01 : Adapted to LXware
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

DIRS   	 =          \
		LXSys		\
		LXMath		\
		LXArray	    \
		LXStkp		\
		LXRand		\
		LXHeap		\
		LXList		\
		LXDict		\
		LXFasta		\
		LXFastq		\
		LXString	\
		LXRegexp	\
		LXPat		\
		LXBio		\
		LXBase64	\
		LXBStream	\
		LXUtils     \
		LX		    \

include ../../../config/makepropagate.targ

include ../../../config/helpbase.targ

